server.port=8083
spring.application.name=servicio-pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/db_pedidos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
